# Site settings
title: Jeff's Games
email: jeffpublic@gmail.com
url: https://games.jeffschomay.com
description: "HTML games portfolio"
skills: "Narrative and Puzzle games"
meta_author: Jeff Schomay

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
#Â - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 3f2046
  secondary: 41abb9
  dark: 333333
  light: eee

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jschomay
  - title: github
    url: http://github.com/jschomay
  - title: cogs
    url: http://elmnarrativeengine.com/

# Build settings
markdown: kramdown
permalink: pretty
